// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using secuenciasAPI.Data;

#nullable disable

namespace secuenciasAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260701164825_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("secuenciasAPI.Models.Carrera", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<long?>("DirectorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("secuenciasAPI.Models.CarreraDocente", b =>
                {
                    b.Property<long>("CarreraId")
                        .HasColumnType("bigint");

                    b.Property<long>("DocenteId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CarreraId", "DocenteId");

                    b.HasIndex("DocenteId");

                    b.ToTable("CarreraDocentes");
                });

            modelBuilder.Entity("secuenciasAPI.Models.CarreraMateria", b =>
                {
                    b.Property<long>("CarreraId")
                        .HasColumnType("bigint");

                    b.Property<long>("MateriaId")
                        .HasColumnType("bigint");

                    b.HasKey("CarreraId", "MateriaId");

                    b.HasIndex("MateriaId");

                    b.ToTable("CarreraMaterias");
                });

            modelBuilder.Entity("secuenciasAPI.Models.Grupo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("CarreraId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Cuatrimestre")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("secuenciasAPI.Models.Materia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("Cuatrimestre")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("secuenciasAPI.Models.Periodo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<short>("Anio")
                        .HasColumnType("smallint");

                    b.Property<string>("PeriodoTexto")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Periodos");
                });

            modelBuilder.Entity("secuenciasAPI.Models.Programa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Contenido")
                        .HasColumnType("json");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<long>("IdMateria")
                        .HasColumnType("bigint");

                    b.Property<long?>("MateriaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.ToTable("Programas");
                });

            modelBuilder.Entity("secuenciasAPI.Models.RevisionSecuencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comentarios")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaRevision")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Resultado")
                        .HasColumnType("int");

                    b.Property<long>("RevisorId")
                        .HasColumnType("bigint");

                    b.Property<long>("SecuenciaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RevisorId");

                    b.HasIndex("SecuenciaId");

                    b.ToTable("RevisionesSecuencia");
                });

            modelBuilder.Entity("secuenciasAPI.Models.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("secuenciasAPI.Models.Secuencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Contenido")
                        .HasColumnType("json");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<long>("DirectorId")
                        .HasColumnType("bigint");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaLimite")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("MateriaId")
                        .HasColumnType("bigint");

                    b.Property<long>("PeriodoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.HasIndex("MateriaId");

                    b.HasIndex("PeriodoId");

                    b.ToTable("Secuencias");
                });

            modelBuilder.Entity("secuenciasAPI.Models.SecuenciaDocente", b =>
                {
                    b.Property<long>("SecuenciaId")
                        .HasColumnType("bigint");

                    b.Property<long>("DocenteId")
                        .HasColumnType("bigint");

                    b.HasKey("SecuenciaId", "DocenteId");

                    b.HasIndex("DocenteId");

                    b.ToTable("SecuenciaDocentes");
                });

            modelBuilder.Entity("secuenciasAPI.Models.SecuenciaGrupo", b =>
                {
                    b.Property<long>("SecuenciaId")
                        .HasColumnType("bigint");

                    b.Property<long>("GrupoId")
                        .HasColumnType("bigint");

                    b.HasKey("SecuenciaId", "GrupoId");

                    b.HasIndex("GrupoId");

                    b.ToTable("SecuenciaGrupos");
                });

            modelBuilder.Entity("secuenciasAPI.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ApellidoMaterno")
                        .HasColumnType("longtext");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RefreshTokenHash")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("secuenciasAPI.Models.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("secuenciasAPI.Models.Carrera", b =>
                {
                    b.HasOne("secuenciasAPI.Models.User", "Director")
                        .WithMany()
                        .HasForeignKey("DirectorId");

                    b.Navigation("Director");
                });

            modelBuilder.Entity("secuenciasAPI.Models.CarreraDocente", b =>
                {
                    b.HasOne("secuenciasAPI.Models.Carrera", "Carrera")
                        .WithMany("CarreraDocentes")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("secuenciasAPI.Models.User", "Docente")
                        .WithMany("CarreraDocentes")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("secuenciasAPI.Models.CarreraMateria", b =>
                {
                    b.HasOne("secuenciasAPI.Models.Carrera", "Carrera")
                        .WithMany("CarreraMaterias")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("secuenciasAPI.Models.Materia", "Materia")
                        .WithMany("CarreraMaterias")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("secuenciasAPI.Models.Grupo", b =>
                {
                    b.HasOne("secuenciasAPI.Models.Carrera", "Carrera")
                        .WithMany("Grupos")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("secuenciasAPI.Models.Programa", b =>
                {
                    b.HasOne("secuenciasAPI.Models.Materia", "Materia")
                        .WithMany("Programas")
                        .HasForeignKey("MateriaId");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("secuenciasAPI.Models.RevisionSecuencia", b =>
                {
                    b.HasOne("secuenciasAPI.Models.User", "Revisor")
                        .WithMany("RevisionesSecuencia")
                        .HasForeignKey("RevisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("secuenciasAPI.Models.Secuencia", "Secuencia")
                        .WithMany("Revisiones")
                        .HasForeignKey("SecuenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revisor");

                    b.Navigation("Secuencia");
                });

            modelBuilder.Entity("secuenciasAPI.Models.Secuencia", b =>
                {
                    b.HasOne("secuenciasAPI.Models.User", "Director")
                        .WithMany("Secuencias")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("secuenciasAPI.Models.Materia", "Materia")
                        .WithMany("Secuencias")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("secuenciasAPI.Models.Periodo", "Periodo")
                        .WithMany("Secuencias")
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");

                    b.Navigation("Materia");

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("secuenciasAPI.Models.SecuenciaDocente", b =>
                {
                    b.HasOne("secuenciasAPI.Models.User", "Docente")
                        .WithMany("SecuenciaDocentes")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("secuenciasAPI.Models.Secuencia", "Secuencia")
                        .WithMany("SecuenciaDocentes")
                        .HasForeignKey("SecuenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("Secuencia");
                });

            modelBuilder.Entity("secuenciasAPI.Models.SecuenciaGrupo", b =>
                {
                    b.HasOne("secuenciasAPI.Models.Grupo", "Grupo")
                        .WithMany("SecuenciaGrupos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("secuenciasAPI.Models.Secuencia", "Secuencia")
                        .WithMany("SecuenciaGrupos")
                        .HasForeignKey("SecuenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Secuencia");
                });

            modelBuilder.Entity("secuenciasAPI.Models.UserRole", b =>
                {
                    b.HasOne("secuenciasAPI.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("secuenciasAPI.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("secuenciasAPI.Models.Carrera", b =>
                {
                    b.Navigation("CarreraDocentes");

                    b.Navigation("CarreraMaterias");

                    b.Navigation("Grupos");
                });

            modelBuilder.Entity("secuenciasAPI.Models.Grupo", b =>
                {
                    b.Navigation("SecuenciaGrupos");
                });

            modelBuilder.Entity("secuenciasAPI.Models.Materia", b =>
                {
                    b.Navigation("CarreraMaterias");

                    b.Navigation("Programas");

                    b.Navigation("Secuencias");
                });

            modelBuilder.Entity("secuenciasAPI.Models.Periodo", b =>
                {
                    b.Navigation("Secuencias");
                });

            modelBuilder.Entity("secuenciasAPI.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("secuenciasAPI.Models.Secuencia", b =>
                {
                    b.Navigation("Revisiones");

                    b.Navigation("SecuenciaDocentes");

                    b.Navigation("SecuenciaGrupos");
                });

            modelBuilder.Entity("secuenciasAPI.Models.User", b =>
                {
                    b.Navigation("CarreraDocentes");

                    b.Navigation("RevisionesSecuencia");

                    b.Navigation("SecuenciaDocentes");

                    b.Navigation("Secuencias");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
