// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plandi.Library.Models;

#nullable disable

namespace Plandi.Library.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260802225959_AddNotificaciones")]
    partial class AddNotificaciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Plandi.Library.Models.Academia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("academias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Academia relacionada con programación, bases de datos y desarrollo web",
                            Nombre = "Desarrollo de Software",
                            PublicId = new Guid("30000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 2L,
                            Activo = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Academia de asignaturas de inglés",
                            Nombre = "Inglés",
                            PublicId = new Guid("30000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("Plandi.Library.Models.AcademiaUsuario", b =>
                {
                    b.Property<long>("AcademiaId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RolEnAcademia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AcademiaId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("academia_usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            AcademiaId = 1L,
                            UsuarioId = 2L,
                            Activo = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolEnAcademia = "Docente"
                        },
                        new
                        {
                            AcademiaId = 1L,
                            UsuarioId = 3L,
                            Activo = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolEnAcademia = "Docente"
                        },
                        new
                        {
                            AcademiaId = 1L,
                            UsuarioId = 4L,
                            Activo = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolEnAcademia = "Revisor"
                        });
                });

            modelBuilder.Entity("Plandi.Library.Models.Asignatura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AcademiaId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Creditos")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Cuatrimestre")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HorasSemana")
                        .HasColumnType("int");

                    b.Property<int>("HorasTotales")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AcademiaId");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("asignaturas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AcademiaId = 1L,
                            Activo = true,
                            Clave = "AW-701",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creditos = 5m,
                            Cuatrimestre = 7,
                            HorasSemana = 5,
                            HorasTotales = 75,
                            Nombre = "Aplicaciones Web",
                            PublicId = new Guid("80000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 2L,
                            AcademiaId = 2L,
                            Activo = true,
                            Clave = "ING-701",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creditos = 4m,
                            Cuatrimestre = 7,
                            HorasSemana = 4,
                            HorasTotales = 60,
                            Nombre = "Inglés VII",
                            PublicId = new Guid("80000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("Plandi.Library.Models.CargaAcademica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AcademiaId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<long>("AsignaturaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("DocenteId")
                        .HasColumnType("bigint");

                    b.Property<long>("GrupoId")
                        .HasColumnType("bigint");

                    b.Property<long>("PeriodoId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("RevisorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AcademiaId");

                    b.HasIndex("AsignaturaId");

                    b.HasIndex("DocenteId");

                    b.HasIndex("GrupoId");

                    b.HasIndex("RevisorId");

                    b.HasIndex("PeriodoId", "GrupoId", "AsignaturaId", "DocenteId")
                        .IsUnique();

                    b.ToTable("carga_academica", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AcademiaId = 1L,
                            Activo = true,
                            AsignaturaId = 1L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            DocenteId = 2L,
                            GrupoId = 1L,
                            PeriodoId = 1L,
                            PublicId = new Guid("90000000-0000-0000-0000-000000000001"),
                            RevisorId = 4L
                        },
                        new
                        {
                            Id = 2L,
                            AcademiaId = 1L,
                            Activo = true,
                            AsignaturaId = 1L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            DocenteId = 3L,
                            GrupoId = 2L,
                            PeriodoId = 1L,
                            PublicId = new Guid("90000000-0000-0000-0000-000000000002"),
                            RevisorId = 4L
                        });
                });

            modelBuilder.Entity("Plandi.Library.Models.Carrera", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nivel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("carreras", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            Clave = "ITI",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nivel = "Ingeniería",
                            Nombre = "Ingeniería en Tecnologías de la Información e Innovación Digital",
                            PublicId = new Guid("40000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("Plandi.Library.Models.CarreraAcademia", b =>
                {
                    b.Property<long>("CarreraId")
                        .HasColumnType("bigint");

                    b.Property<long>("AcademiaId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CarreraId", "AcademiaId");

                    b.HasIndex("AcademiaId");

                    b.ToTable("carrera_academias", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.Chat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("PlaneacionDidacticaId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlaneacionDidacticaId")
                        .IsUnique();

                    b.ToTable("chats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaneacionDidacticaId = 1L,
                            PublicId = new Guid("ffffffff-0000-0000-0000-000000000001"),
                            Titulo = "Chat - Planeación Aplicaciones Web"
                        });
                });

            modelBuilder.Entity("Plandi.Library.Models.ChatMensaje", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditadoAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EliminadoAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoMensaje")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UsuarioId");

                    b.ToTable("chat_mensajes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            ChatId = 1L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mensaje = "Favor de revisar que las actividades correspondan con los resultados de aprendizaje.",
                            PublicId = new Guid("11111111-aaaa-0000-0000-000000000001"),
                            TipoMensaje = "OBSERVACION",
                            UsuarioId = 4L
                        },
                        new
                        {
                            Id = 2L,
                            Activo = true,
                            ChatId = 1L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mensaje = "De acuerdo, revisaremos la Unidad I y ajustaremos las evidencias.",
                            PublicId = new Guid("11111111-aaaa-0000-0000-000000000002"),
                            TipoMensaje = "TEXTO",
                            UsuarioId = 2L
                        });
                });

            modelBuilder.Entity("Plandi.Library.Models.ChatParticipante", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RolEnChat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ChatId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("chat_participantes", (string)null);

                    b.HasData(
                        new
                        {
                            ChatId = 1L,
                            UsuarioId = 2L,
                            Activo = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolEnChat = "DOCENTE"
                        },
                        new
                        {
                            ChatId = 1L,
                            UsuarioId = 3L,
                            Activo = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolEnChat = "DOCENTE"
                        },
                        new
                        {
                            ChatId = 1L,
                            UsuarioId = 4L,
                            Activo = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolEnChat = "REVISOR"
                        });
                });

            modelBuilder.Entity("Plandi.Library.Models.CicloEscolar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("ciclos_escolares", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaFin = new DateTime(2027, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "2026-2027",
                            PublicId = new Guid("50000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("Plandi.Library.Models.Documento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashSha256")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NombreGuardado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RutaStorage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("SubidoPorId")
                        .HasColumnType("bigint");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("HashSha256");

                    b.HasIndex("SubidoPorId");

                    b.HasIndex("TipoDocumento");

                    b.ToTable("documentos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "Procesado",
                            Extension = ".pdf",
                            FechaSubida = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HashSha256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
                            MimeType = "application/pdf",
                            NombreGuardado = "programa-aplicaciones-web-dev.pdf",
                            NombreOriginal = "programa-aplicaciones-web.pdf",
                            PublicId = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            RutaStorage = "documentos/programas-asignatura/2026/programa-aplicaciones-web-dev.pdf",
                            SubidoPorId = 1L,
                            TamanoBytes = 204800L,
                            TipoDocumento = "ProgramaAsignatura",
                            Titulo = "Programa de Asignatura - Aplicaciones Web"
                        });
                });

            modelBuilder.Entity("Plandi.Library.Models.Grupo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<long>("CarreraId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Cuatrimestre")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("PeriodoId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("PeriodoId", "Nombre")
                        .IsUnique();

                    b.ToTable("grupos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            CarreraId = 1L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Cuatrimestre = 7,
                            Nombre = "ITI-701",
                            PeriodoId = 1L,
                            PublicId = new Guid("70000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 2L,
                            Activo = true,
                            CarreraId = 1L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Cuatrimestre = 7,
                            Nombre = "ITI-702",
                            PeriodoId = 1L,
                            PublicId = new Guid("70000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("Plandi.Library.Models.Notificacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLectura")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Leida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PlaneacionDidacticaId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PlaneacionDidacticaId");

                    b.HasIndex("UsuarioId", "Leida", "CreatedAt");

                    b.ToTable("notificaciones", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.Periodo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<long>("CicloEscolarId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CicloEscolarId", "Nombre")
                        .IsUnique();

                    b.ToTable("periodos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            CicloEscolarId = 1L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaFin = new DateTime(2026, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Septiembre-Diciembre 2026",
                            PublicId = new Guid("60000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionActividad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstrategiaAprendizaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstrategiaEnsenanza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Evidencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Horas")
                        .HasColumnType("int");

                    b.Property<string>("InstrumentoEvaluacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<long>("PlaneacionUnidadId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PorcentajeEvaluacion")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Semana")
                        .HasColumnType("int");

                    b.Property<string>("TipoActividad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PlaneacionUnidadId", "Orden");

                    b.ToTable("planeacion_actividades", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 2L,
                            Descripcion = "Presentación de conceptos básicos de aplicaciones web.",
                            EstrategiaAprendizaje = "Discusión grupal y análisis de ejemplos.",
                            EstrategiaEnsenanza = "Exposición guiada y preguntas detonadoras.",
                            Evidencia = "Mapa conceptual de arquitectura web.",
                            Horas = 2,
                            InstrumentoEvaluacion = "Lista de cotejo",
                            Orden = 1,
                            PlaneacionUnidadId = 1L,
                            PorcentajeEvaluacion = 10m,
                            PublicId = new Guid("eeeeeeee-0000-0000-0000-000000000001"),
                            Semana = 1,
                            TipoActividad = "APERTURA"
                        },
                        new
                        {
                            Id = 2L,
                            Activo = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 3L,
                            Descripcion = "Construcción de una API REST con .NET por capas.",
                            EstrategiaAprendizaje = "Desarrollo guiado de endpoints.",
                            EstrategiaEnsenanza = "Demostración práctica.",
                            Evidencia = "API funcional con controladores y servicios.",
                            Horas = 6,
                            InstrumentoEvaluacion = "Rúbrica",
                            Orden = 1,
                            PlaneacionUnidadId = 2L,
                            PorcentajeEvaluacion = 30m,
                            PublicId = new Guid("eeeeeeee-0000-0000-0000-000000000002"),
                            Semana = 4,
                            TipoActividad = "DESARROLLO"
                        });
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionDidactica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AcademiaId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<long>("AsignaturaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaUltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<long>("PeriodoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProgramaAsignaturaId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("RevisorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long?>("UltimaModificacionPorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AcademiaId");

                    b.HasIndex("AsignaturaId");

                    b.HasIndex("Estado");

                    b.HasIndex("ProgramaAsignaturaId");

                    b.HasIndex("RevisorId");

                    b.HasIndex("UltimaModificacionPorId");

                    b.HasIndex("PeriodoId", "AsignaturaId")
                        .IsUnique();

                    b.ToTable("planeaciones_didacticas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AcademiaId = 1L,
                            Activo = true,
                            AsignaturaId = 1L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            Estado = "EnProceso",
                            FechaUltimaModificacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodoId = 1L,
                            ProgramaAsignaturaId = 1L,
                            PublicId = new Guid("cccccccc-0000-0000-0000-000000000001"),
                            RevisorId = 4L,
                            Titulo = "Planeación Didáctica - Aplicaciones Web - Septiembre-Diciembre 2026",
                            UltimaModificacionPorId = 2L
                        });
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionDocente", b =>
                {
                    b.Property<long>("PlaneacionDidacticaId")
                        .HasColumnType("bigint");

                    b.Property<long>("DocenteId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PlaneacionDidacticaId", "DocenteId");

                    b.HasIndex("DocenteId");

                    b.ToTable("planeacion_docentes", (string)null);

                    b.HasData(
                        new
                        {
                            PlaneacionDidacticaId = 1L,
                            DocenteId = 2L,
                            Activo = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PlaneacionDidacticaId = 1L,
                            DocenteId = 3L,
                            Activo = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionGrupo", b =>
                {
                    b.Property<long>("PlaneacionDidacticaId")
                        .HasColumnType("bigint");

                    b.Property<long>("GrupoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PlaneacionDidacticaId", "GrupoId");

                    b.HasIndex("GrupoId");

                    b.ToTable("planeacion_grupos", (string)null);

                    b.HasData(
                        new
                        {
                            PlaneacionDidacticaId = 1L,
                            GrupoId = 1L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PlaneacionDidacticaId = 1L,
                            GrupoId = 2L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionObservacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("PlaneacionDidacticaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PlaneacionUnidadId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("RevisorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlaneacionDidacticaId");

                    b.HasIndex("PlaneacionUnidadId");

                    b.HasIndex("RevisorId");

                    b.ToTable("planeacion_observaciones", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            Comentario = "La evidencia de la Unidad I debe estar mejor relacionada con el resultado de aprendizaje.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "ABIERTA",
                            PlaneacionDidacticaId = 1L,
                            PlaneacionUnidadId = 1L,
                            PublicId = new Guid("22222222-aaaa-0000-0000-000000000001"),
                            RevisorId = 4L
                        });
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionUnidad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Horas")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<long>("PlaneacionDidacticaId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResultadoAprendizaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UltimaModificacionPorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UltimaModificacionPorId");

                    b.HasIndex("PlaneacionDidacticaId", "Orden")
                        .IsUnique();

                    b.ToTable("planeacion_unidades", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaUltimaModificacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Horas = 20,
                            Nombre = "Introducción a las aplicaciones web",
                            Numero = "I",
                            Orden = 1,
                            PlaneacionDidacticaId = 1L,
                            PublicId = new Guid("dddddddd-0000-0000-0000-000000000001"),
                            ResultadoAprendizaje = "El alumno identificará los componentes básicos de una aplicación web.",
                            UltimaModificacionPorId = 2L
                        },
                        new
                        {
                            Id = 2L,
                            Activo = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaUltimaModificacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Horas = 30,
                            Nombre = "Desarrollo de APIs",
                            Numero = "II",
                            Orden = 2,
                            PlaneacionDidacticaId = 1L,
                            PublicId = new Guid("dddddddd-0000-0000-0000-000000000002"),
                            ResultadoAprendizaje = "El alumno desarrollará servicios web usando arquitectura por capas.",
                            UltimaModificacionPorId = 3L
                        });
                });

            modelBuilder.Entity("Plandi.Library.Models.ProgramaAsignatura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AcademiaId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<long?>("AsignaturaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Carrera")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClaveAsignatura")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Competencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Creditos")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("Cuatrimestre")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("DocumentoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FechaUltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HorasSemana")
                        .HasColumnType("int");

                    b.Property<int?>("HorasTotales")
                        .HasColumnType("int");

                    b.Property<string>("JsonExtraido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreAsignatura")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Proposito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TextoExtraido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UltimaModificacionPorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AcademiaId");

                    b.HasIndex("AsignaturaId");

                    b.HasIndex("ClaveAsignatura");

                    b.HasIndex("DocumentoId")
                        .IsUnique();

                    b.HasIndex("NombreAsignatura");

                    b.HasIndex("UltimaModificacionPorId");

                    b.ToTable("programas_asignatura", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AcademiaId = 1L,
                            Activo = true,
                            AsignaturaId = 1L,
                            Carrera = "Ingeniería en Tecnologías de la Información e Innovación Digital",
                            ClaveAsignatura = "AW-701",
                            Competencia = "Desarrollar aplicaciones web utilizando tecnologías actuales y buenas prácticas de programación.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creditos = 5m,
                            Cuatrimestre = 7,
                            DocumentoId = 1L,
                            FechaUltimaModificacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HorasSemana = 5,
                            HorasTotales = 75,
                            JsonExtraido = "{\n  \"unidades\": [\n    {\n      \"numero\": \"I\",\n      \"nombre\": \"Introducción a las aplicaciones web\",\n      \"resultado_aprendizaje\": \"El alumno identificará los componentes básicos de una aplicación web.\",\n      \"temas\": [\n        \"Cliente-servidor\",\n        \"HTTP\",\n        \"APIs REST\"\n      ]\n    },\n    {\n      \"numero\": \"II\",\n      \"nombre\": \"Desarrollo de APIs\",\n      \"resultado_aprendizaje\": \"El alumno desarrollará servicios web usando arquitectura por capas.\",\n      \"temas\": [\n        \"Controladores\",\n        \"Servicios\",\n        \"DTOs\",\n        \"Entity Framework Core\"\n      ]\n    }\n  ]\n}",
                            NombreAsignatura = "Aplicaciones Web",
                            Proposito = "El alumno desarrollará aplicaciones web funcionales aplicando arquitectura por capas.",
                            PublicId = new Guid("bbbbbbbb-0000-0000-0000-000000000001"),
                            TextoExtraido = "Texto extraído de prueba del programa de asignatura.",
                            UltimaModificacionPorId = 1L
                        });
                });

            modelBuilder.Entity("Plandi.Library.Models.Rol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Usuario con acceso total al sistema",
                            Nombre = "Administrador",
                            PublicId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 2L,
                            Activo = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Profesor que participa en planeaciones didácticas",
                            Nombre = "Docente",
                            PublicId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = 3L,
                            Activo = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Usuario encargado de revisar planeaciones didácticas",
                            Nombre = "Revisor",
                            PublicId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = 4L,
                            Activo = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Usuario encargado de aprobación final",
                            Nombre = "Director",
                            PublicId = new Guid("10000000-0000-0000-0000-000000000004")
                        });
                });

            modelBuilder.Entity("Plandi.Library.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            ApellidoPaterno = "Sistema",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@uth.edu.mx",
                            Nombre = "Admin",
                            PasswordHash = "DEV_HASH_SOLO_PRUEBAS",
                            PublicId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 2L,
                            Activo = true,
                            ApellidoPaterno = "Pérez",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "juan.perez@uth.edu.mx",
                            Nombre = "Juan",
                            PasswordHash = "DEV_HASH_SOLO_PRUEBAS",
                            PublicId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = 3L,
                            Activo = true,
                            ApellidoPaterno = "Torres",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ana.torres@uth.edu.mx",
                            Nombre = "Ana",
                            PasswordHash = "DEV_HASH_SOLO_PRUEBAS",
                            PublicId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = 4L,
                            Activo = true,
                            ApellidoPaterno = "López",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maria.lopez@uth.edu.mx",
                            Nombre = "María",
                            PasswordHash = "DEV_HASH_SOLO_PRUEBAS",
                            PublicId = new Guid("20000000-0000-0000-0000-000000000004")
                        });
                });

            modelBuilder.Entity("Plandi.Library.Models.UsuarioRol", b =>
                {
                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<long>("RolId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("usuario_roles", (string)null);

                    b.HasData(
                        new
                        {
                            UsuarioId = 1L,
                            RolId = 1L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsuarioId = 2L,
                            RolId = 2L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsuarioId = 3L,
                            RolId = 2L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsuarioId = 4L,
                            RolId = 3L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Plandi.Library.Models.AcademiaUsuario", b =>
                {
                    b.HasOne("Plandi.Library.Models.Academia", "Academia")
                        .WithMany("AcademiaUsuarios")
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Usuario", "Usuario")
                        .WithMany("AcademiaUsuarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Academia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Plandi.Library.Models.Asignatura", b =>
                {
                    b.HasOne("Plandi.Library.Models.Academia", "Academia")
                        .WithMany("Asignaturas")
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Academia");
                });

            modelBuilder.Entity("Plandi.Library.Models.CargaAcademica", b =>
                {
                    b.HasOne("Plandi.Library.Models.Academia", "Academia")
                        .WithMany()
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Plandi.Library.Models.Asignatura", "Asignatura")
                        .WithMany("CargasAcademicas")
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Usuario", "Docente")
                        .WithMany()
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Grupo", "Grupo")
                        .WithMany("CargasAcademicas")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Periodo", "Periodo")
                        .WithMany()
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Usuario", "Revisor")
                        .WithMany()
                        .HasForeignKey("RevisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Academia");

                    b.Navigation("Asignatura");

                    b.Navigation("Docente");

                    b.Navigation("Grupo");

                    b.Navigation("Periodo");

                    b.Navigation("Revisor");
                });

            modelBuilder.Entity("Plandi.Library.Models.CarreraAcademia", b =>
                {
                    b.HasOne("Plandi.Library.Models.Academia", "Academia")
                        .WithMany("CarreraAcademias")
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Carrera", "Carrera")
                        .WithMany("CarreraAcademias")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Academia");

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("Plandi.Library.Models.Chat", b =>
                {
                    b.HasOne("Plandi.Library.Models.PlaneacionDidactica", "PlaneacionDidactica")
                        .WithMany("Chats")
                        .HasForeignKey("PlaneacionDidacticaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlaneacionDidactica");
                });

            modelBuilder.Entity("Plandi.Library.Models.ChatMensaje", b =>
                {
                    b.HasOne("Plandi.Library.Models.Chat", "Chat")
                        .WithMany("Mensajes")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Plandi.Library.Models.ChatParticipante", b =>
                {
                    b.HasOne("Plandi.Library.Models.Chat", "Chat")
                        .WithMany("Participantes")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Plandi.Library.Models.Documento", b =>
                {
                    b.HasOne("Plandi.Library.Models.Usuario", "SubidoPor")
                        .WithMany()
                        .HasForeignKey("SubidoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubidoPor");
                });

            modelBuilder.Entity("Plandi.Library.Models.Grupo", b =>
                {
                    b.HasOne("Plandi.Library.Models.Carrera", "Carrera")
                        .WithMany("Grupos")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Periodo", "Periodo")
                        .WithMany("Grupos")
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("Plandi.Library.Models.Notificacion", b =>
                {
                    b.HasOne("Plandi.Library.Models.PlaneacionDidactica", "PlaneacionDidactica")
                        .WithMany()
                        .HasForeignKey("PlaneacionDidacticaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Plandi.Library.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlaneacionDidactica");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Plandi.Library.Models.Periodo", b =>
                {
                    b.HasOne("Plandi.Library.Models.CicloEscolar", "CicloEscolar")
                        .WithMany("Periodos")
                        .HasForeignKey("CicloEscolarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CicloEscolar");
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionActividad", b =>
                {
                    b.HasOne("Plandi.Library.Models.PlaneacionUnidad", "PlaneacionUnidad")
                        .WithMany("Actividades")
                        .HasForeignKey("PlaneacionUnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlaneacionUnidad");
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionDidactica", b =>
                {
                    b.HasOne("Plandi.Library.Models.Academia", "Academia")
                        .WithMany()
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Plandi.Library.Models.Asignatura", "Asignatura")
                        .WithMany("PlaneacionesDidacticas")
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Periodo", "Periodo")
                        .WithMany()
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.ProgramaAsignatura", "ProgramaAsignatura")
                        .WithMany()
                        .HasForeignKey("ProgramaAsignaturaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Plandi.Library.Models.Usuario", "Revisor")
                        .WithMany()
                        .HasForeignKey("RevisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Plandi.Library.Models.Usuario", "UltimaModificacionPor")
                        .WithMany()
                        .HasForeignKey("UltimaModificacionPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Academia");

                    b.Navigation("Asignatura");

                    b.Navigation("Periodo");

                    b.Navigation("ProgramaAsignatura");

                    b.Navigation("Revisor");

                    b.Navigation("UltimaModificacionPor");
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionDocente", b =>
                {
                    b.HasOne("Plandi.Library.Models.Usuario", "Docente")
                        .WithMany()
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.PlaneacionDidactica", "PlaneacionDidactica")
                        .WithMany("PlaneacionDocentes")
                        .HasForeignKey("PlaneacionDidacticaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("PlaneacionDidactica");
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionGrupo", b =>
                {
                    b.HasOne("Plandi.Library.Models.Grupo", "Grupo")
                        .WithMany("PlaneacionGrupos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.PlaneacionDidactica", "PlaneacionDidactica")
                        .WithMany("PlaneacionGrupos")
                        .HasForeignKey("PlaneacionDidacticaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("PlaneacionDidactica");
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionObservacion", b =>
                {
                    b.HasOne("Plandi.Library.Models.PlaneacionDidactica", "PlaneacionDidactica")
                        .WithMany()
                        .HasForeignKey("PlaneacionDidacticaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.PlaneacionUnidad", "PlaneacionUnidad")
                        .WithMany()
                        .HasForeignKey("PlaneacionUnidadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Plandi.Library.Models.Usuario", "Revisor")
                        .WithMany()
                        .HasForeignKey("RevisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlaneacionDidactica");

                    b.Navigation("PlaneacionUnidad");

                    b.Navigation("Revisor");
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionUnidad", b =>
                {
                    b.HasOne("Plandi.Library.Models.PlaneacionDidactica", "PlaneacionDidactica")
                        .WithMany("Unidades")
                        .HasForeignKey("PlaneacionDidacticaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Usuario", "UltimaModificacionPor")
                        .WithMany()
                        .HasForeignKey("UltimaModificacionPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PlaneacionDidactica");

                    b.Navigation("UltimaModificacionPor");
                });

            modelBuilder.Entity("Plandi.Library.Models.ProgramaAsignatura", b =>
                {
                    b.HasOne("Plandi.Library.Models.Academia", "Academia")
                        .WithMany()
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Plandi.Library.Models.Asignatura", "Asignatura")
                        .WithMany("ProgramasAsignatura")
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Plandi.Library.Models.Documento", "Documento")
                        .WithOne("ProgramaAsignatura")
                        .HasForeignKey("Plandi.Library.Models.ProgramaAsignatura", "DocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Usuario", "UltimaModificacionPor")
                        .WithMany()
                        .HasForeignKey("UltimaModificacionPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Academia");

                    b.Navigation("Asignatura");

                    b.Navigation("Documento");

                    b.Navigation("UltimaModificacionPor");
                });

            modelBuilder.Entity("Plandi.Library.Models.UsuarioRol", b =>
                {
                    b.HasOne("Plandi.Library.Models.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Plandi.Library.Models.Academia", b =>
                {
                    b.Navigation("AcademiaUsuarios");

                    b.Navigation("Asignaturas");

                    b.Navigation("CarreraAcademias");
                });

            modelBuilder.Entity("Plandi.Library.Models.Asignatura", b =>
                {
                    b.Navigation("CargasAcademicas");

                    b.Navigation("PlaneacionesDidacticas");

                    b.Navigation("ProgramasAsignatura");
                });

            modelBuilder.Entity("Plandi.Library.Models.Carrera", b =>
                {
                    b.Navigation("CarreraAcademias");

                    b.Navigation("Grupos");
                });

            modelBuilder.Entity("Plandi.Library.Models.Chat", b =>
                {
                    b.Navigation("Mensajes");

                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("Plandi.Library.Models.CicloEscolar", b =>
                {
                    b.Navigation("Periodos");
                });

            modelBuilder.Entity("Plandi.Library.Models.Documento", b =>
                {
                    b.Navigation("ProgramaAsignatura");
                });

            modelBuilder.Entity("Plandi.Library.Models.Grupo", b =>
                {
                    b.Navigation("CargasAcademicas");

                    b.Navigation("PlaneacionGrupos");
                });

            modelBuilder.Entity("Plandi.Library.Models.Periodo", b =>
                {
                    b.Navigation("Grupos");
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionDidactica", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("PlaneacionDocentes");

                    b.Navigation("PlaneacionGrupos");

                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionUnidad", b =>
                {
                    b.Navigation("Actividades");
                });

            modelBuilder.Entity("Plandi.Library.Models.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Plandi.Library.Models.Usuario", b =>
                {
                    b.Navigation("AcademiaUsuarios");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
