// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plandi.Library.Models;

#nullable disable

namespace Plandi.Library.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817175217_AddUserDeviceTokens")]
    partial class AddUserDeviceTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Plandi.Library.Models.Academia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("academias", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.AcademiaUsuario", b =>
                {
                    b.Property<long>("AcademiaId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("AcademiaId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("academia_usuarios", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.Asignatura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AcademiaId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Creditos")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Cuatrimestre")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HorasSemana")
                        .HasColumnType("int");

                    b.Property<int>("HorasTotales")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AcademiaId");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("asignaturas", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.CargaAcademica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AcademiaId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<long>("AsignaturaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("DocenteId")
                        .HasColumnType("bigint");

                    b.Property<long>("GrupoId")
                        .HasColumnType("bigint");

                    b.Property<long>("PeriodoId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("RevisorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AcademiaId");

                    b.HasIndex("AsignaturaId");

                    b.HasIndex("DocenteId");

                    b.HasIndex("GrupoId");

                    b.HasIndex("RevisorId");

                    b.HasIndex("PeriodoId", "GrupoId", "AsignaturaId", "DocenteId")
                        .IsUnique()
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("carga_academica", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.Carrera", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nivel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("carreras", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.Chat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("PlaneacionDidacticaId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlaneacionDidacticaId", "Titulo")
                        .IsUnique()
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("chats", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.ChatMensaje", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditadoAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EliminadoAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoMensaje")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UsuarioId");

                    b.ToTable("chat_mensajes", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.ChatParticipante", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RolEnChat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ChatId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("chat_participantes", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.CicloEscolar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("ciclos_escolares", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.Documento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashSha256")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NombreGuardado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RutaStorage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("SubidoPorId")
                        .HasColumnType("bigint");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("HashSha256");

                    b.HasIndex("SubidoPorId");

                    b.HasIndex("TipoDocumento");

                    b.ToTable("documentos", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.Grupo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<long>("CarreraId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("Cuatrimestre")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("PeriodoId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("PeriodoId", "Nombre")
                        .IsUnique()
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("grupos", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.Periodo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<long>("CicloEscolarId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaFin");

                    b.HasIndex("FechaInicio");

                    b.HasIndex("CicloEscolarId", "Nombre")
                        .IsUnique()
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("periodos", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionCaratula", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CompetenciaAsignatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Creditos")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("Cuatrimestre")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Docentes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grupos")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("HorasSaber")
                        .HasColumnType("int");

                    b.Property<int?>("HorasSaberHacer")
                        .HasColumnType("int");

                    b.Property<int?>("HorasSemana")
                        .HasColumnType("int");

                    b.Property<int?>("HorasTotales")
                        .HasColumnType("int");

                    b.Property<string>("Modalidad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreAsignatura")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PeriodoEscolar")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("PlaneacionDidacticaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProgramaAsignaturaId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProgramaEducativo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PropositoAsignatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoCompetencia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("UltimaModificacionPorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlaneacionDidacticaId")
                        .IsUnique();

                    b.HasIndex("ProgramaAsignaturaId");

                    b.HasIndex("UltimaModificacionPorId");

                    b.ToTable("planeacion_caratulas", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionDidactica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AcademiaId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<long>("AsignaturaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaUltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<long>("PeriodoId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("RevisorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UltimaModificacionPorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AcademiaId");

                    b.HasIndex("AsignaturaId");

                    b.HasIndex("Estado");

                    b.HasIndex("RevisorId");

                    b.HasIndex("UltimaModificacionPorId");

                    b.HasIndex("PeriodoId", "AsignaturaId")
                        .IsUnique();

                    b.ToTable("planeaciones_didacticas", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionEtapaSecuencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fase")
                        .HasColumnType("int");

                    b.Property<long>("PlaneacionUnidadId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlaneacionUnidadId", "Fase")
                        .IsUnique();

                    b.ToTable("planeacion_etapas_secuencia", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionEvaluacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("AgenteEvaluador")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvidenciaAprendizaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fase")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaUltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("InstrumentoEvaluacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int?>("PeriodoSemanas")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<long>("PlaneacionUnidadId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Ponderacion")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResultadoAprendizaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipoEvaluacion")
                        .HasColumnType("int");

                    b.Property<long?>("UltimaModificacionPorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UltimaModificacionPorId");

                    b.HasIndex("PlaneacionUnidadId", "Orden");

                    b.ToTable("planeacion_evaluaciones", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionObservacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaAtendida")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRevision")
                        .HasColumnType("datetime2");

                    b.Property<long>("PlaneacionDidacticaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PlaneacionEvaluacionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PlaneacionSecuenciaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PlaneacionTemaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PlaneacionUnidadId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("RevisorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Seccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlaneacionDidacticaId");

                    b.HasIndex("PlaneacionUnidadId");

                    b.HasIndex("RevisorId");

                    b.ToTable("planeacion_observaciones", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionReferencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<long>("PlaneacionDidacticaId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenciaAPA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UltimaModificacionPorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UltimaModificacionPorId");

                    b.HasIndex("PlaneacionDidacticaId", "Orden");

                    b.ToTable("planeacion_referencias", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionSecuencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActividadDocente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActividadEstudiante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estrategia")
                        .HasColumnType("int");

                    b.Property<string>("EvidenciaAprendizaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fase")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaUltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MediosMateriales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MetodoTecnica")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<long>("PlaneacionEtapaSecuenciaId")
                        .HasColumnType("bigint");

                    b.Property<long>("PlaneacionUnidadId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("UltimaModificacionPorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlaneacionUnidadId");

                    b.HasIndex("UltimaModificacionPorId");

                    b.HasIndex("PlaneacionEtapaSecuenciaId", "Orden")
                        .IsUnique();

                    b.ToTable("planeacion_secuencias", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionSecuenciaRecurso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<long>("PlaneacionSecuenciaId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlaneacionSecuenciaId", "Orden")
                        .IsUnique();

                    b.ToTable("planeacion_secuencia_recursos", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionTema", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<long>("PlaneacionUnidadId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SaberConceptual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaberHacer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaberSer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long?>("UltimaModificacionPorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UltimaModificacionPorId");

                    b.HasIndex("PlaneacionUnidadId", "Orden");

                    b.ToTable("planeacion_temas", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("DocumentoId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Activa")
                        .IsUnique()
                        .HasFilter("[Activa] = 1");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("plantillas_planeacion", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionUnidad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HorasSaber")
                        .HasColumnType("int");

                    b.Property<int?>("HorasSaberHacer")
                        .HasColumnType("int");

                    b.Property<int?>("HorasTotales")
                        .HasColumnType("int");

                    b.Property<string>("NombreUnidad")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("NumeroUnidad")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<long>("PlaneacionDidacticaId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PorcentajeUnidad")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PropositoEsperado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("UltimaModificacionPorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UltimaModificacionPorId");

                    b.HasIndex("PlaneacionDidacticaId", "Orden")
                        .IsUnique();

                    b.ToTable("planeacion_unidades", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.ProgramaAsignatura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AcademiaId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<long?>("AsignaturaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Carrera")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClaveAsignatura")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Competencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Creditos")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("Cuatrimestre")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("DocumentoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FechaUltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HorasSemana")
                        .HasColumnType("int");

                    b.Property<int?>("HorasTotales")
                        .HasColumnType("int");

                    b.Property<string>("JsonExtraido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreAsignatura")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Proposito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TextoExtraido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UltimaModificacionPorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AcademiaId");

                    b.HasIndex("AsignaturaId");

                    b.HasIndex("ClaveAsignatura");

                    b.HasIndex("DocumentoId")
                        .IsUnique();

                    b.HasIndex("NombreAsignatura");

                    b.HasIndex("UltimaModificacionPorId");

                    b.ToTable("programas_asignatura", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Plandi.Library.Models.Rol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Docente responsable de sus planeaciones.",
                            Nombre = "Docente",
                            PublicId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 2L,
                            Activo = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Usuario que revisa planeaciones asignadas.",
                            Nombre = "Revisor",
                            PublicId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = 3L,
                            Activo = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Usuario que administra asignaciones y roles.",
                            Nombre = "Director",
                            PublicId = new Guid("10000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("Plandi.Library.Models.UserDeviceToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DeviceToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("user_device_tokens", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("TwoFactorSecretKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.UsuarioRol", b =>
                {
                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<long>("RolId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("usuario_roles", (string)null);
                });

            modelBuilder.Entity("Plandi.Library.Models.AcademiaUsuario", b =>
                {
                    b.HasOne("Plandi.Library.Models.Academia", "Academia")
                        .WithMany("AcademiaUsuarios")
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Usuario", "Usuario")
                        .WithMany("AcademiaUsuarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Academia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Plandi.Library.Models.Asignatura", b =>
                {
                    b.HasOne("Plandi.Library.Models.Academia", "Academia")
                        .WithMany("Asignaturas")
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Academia");
                });

            modelBuilder.Entity("Plandi.Library.Models.CargaAcademica", b =>
                {
                    b.HasOne("Plandi.Library.Models.Academia", "Academia")
                        .WithMany()
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Plandi.Library.Models.Asignatura", "Asignatura")
                        .WithMany("CargasAcademicas")
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Usuario", "Docente")
                        .WithMany()
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Grupo", "Grupo")
                        .WithMany("CargasAcademicas")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Periodo", "Periodo")
                        .WithMany()
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Usuario", "Revisor")
                        .WithMany()
                        .HasForeignKey("RevisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Academia");

                    b.Navigation("Asignatura");

                    b.Navigation("Docente");

                    b.Navigation("Grupo");

                    b.Navigation("Periodo");

                    b.Navigation("Revisor");
                });

            modelBuilder.Entity("Plandi.Library.Models.Chat", b =>
                {
                    b.HasOne("Plandi.Library.Models.PlaneacionDidactica", "PlaneacionDidactica")
                        .WithMany("Chats")
                        .HasForeignKey("PlaneacionDidacticaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlaneacionDidactica");
                });

            modelBuilder.Entity("Plandi.Library.Models.ChatMensaje", b =>
                {
                    b.HasOne("Plandi.Library.Models.Chat", "Chat")
                        .WithMany("Mensajes")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Plandi.Library.Models.ChatParticipante", b =>
                {
                    b.HasOne("Plandi.Library.Models.Chat", "Chat")
                        .WithMany("Participantes")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Plandi.Library.Models.Documento", b =>
                {
                    b.HasOne("Plandi.Library.Models.Usuario", "SubidoPor")
                        .WithMany()
                        .HasForeignKey("SubidoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubidoPor");
                });

            modelBuilder.Entity("Plandi.Library.Models.Grupo", b =>
                {
                    b.HasOne("Plandi.Library.Models.Carrera", "Carrera")
                        .WithMany("Grupos")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Periodo", "Periodo")
                        .WithMany("Grupos")
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("Plandi.Library.Models.Periodo", b =>
                {
                    b.HasOne("Plandi.Library.Models.CicloEscolar", "CicloEscolar")
                        .WithMany("Periodos")
                        .HasForeignKey("CicloEscolarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CicloEscolar");
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionCaratula", b =>
                {
                    b.HasOne("Plandi.Library.Models.PlaneacionDidactica", "PlaneacionDidactica")
                        .WithOne("Caratula")
                        .HasForeignKey("Plandi.Library.Models.PlaneacionCaratula", "PlaneacionDidacticaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.ProgramaAsignatura", "ProgramaAsignatura")
                        .WithMany()
                        .HasForeignKey("ProgramaAsignaturaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Plandi.Library.Models.Usuario", "UltimaModificacionPor")
                        .WithMany()
                        .HasForeignKey("UltimaModificacionPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PlaneacionDidactica");

                    b.Navigation("ProgramaAsignatura");

                    b.Navigation("UltimaModificacionPor");
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionDidactica", b =>
                {
                    b.HasOne("Plandi.Library.Models.Academia", "Academia")
                        .WithMany()
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Plandi.Library.Models.Asignatura", "Asignatura")
                        .WithMany("PlaneacionesDidacticas")
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Periodo", "Periodo")
                        .WithMany()
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Usuario", "Revisor")
                        .WithMany()
                        .HasForeignKey("RevisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Plandi.Library.Models.Usuario", "UltimaModificacionPor")
                        .WithMany()
                        .HasForeignKey("UltimaModificacionPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Academia");

                    b.Navigation("Asignatura");

                    b.Navigation("Periodo");

                    b.Navigation("Revisor");

                    b.Navigation("UltimaModificacionPor");
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionEtapaSecuencia", b =>
                {
                    b.HasOne("Plandi.Library.Models.PlaneacionUnidad", "PlaneacionUnidad")
                        .WithMany("EtapasSecuencia")
                        .HasForeignKey("PlaneacionUnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlaneacionUnidad");
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionEvaluacion", b =>
                {
                    b.HasOne("Plandi.Library.Models.PlaneacionUnidad", "PlaneacionUnidad")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("PlaneacionUnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Usuario", "UltimaModificacionPor")
                        .WithMany()
                        .HasForeignKey("UltimaModificacionPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PlaneacionUnidad");

                    b.Navigation("UltimaModificacionPor");
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionObservacion", b =>
                {
                    b.HasOne("Plandi.Library.Models.PlaneacionDidactica", "PlaneacionDidactica")
                        .WithMany("Observaciones")
                        .HasForeignKey("PlaneacionDidacticaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.PlaneacionUnidad", "PlaneacionUnidad")
                        .WithMany()
                        .HasForeignKey("PlaneacionUnidadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Plandi.Library.Models.Usuario", "Revisor")
                        .WithMany()
                        .HasForeignKey("RevisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlaneacionDidactica");

                    b.Navigation("PlaneacionUnidad");

                    b.Navigation("Revisor");
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionReferencia", b =>
                {
                    b.HasOne("Plandi.Library.Models.PlaneacionDidactica", "PlaneacionDidactica")
                        .WithMany("Referencias")
                        .HasForeignKey("PlaneacionDidacticaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Usuario", "UltimaModificacionPor")
                        .WithMany()
                        .HasForeignKey("UltimaModificacionPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PlaneacionDidactica");

                    b.Navigation("UltimaModificacionPor");
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionSecuencia", b =>
                {
                    b.HasOne("Plandi.Library.Models.PlaneacionEtapaSecuencia", "EtapaSecuencia")
                        .WithMany("Elementos")
                        .HasForeignKey("PlaneacionEtapaSecuenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.PlaneacionUnidad", "PlaneacionUnidad")
                        .WithMany("Secuencias")
                        .HasForeignKey("PlaneacionUnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Usuario", "UltimaModificacionPor")
                        .WithMany()
                        .HasForeignKey("UltimaModificacionPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EtapaSecuencia");

                    b.Navigation("PlaneacionUnidad");

                    b.Navigation("UltimaModificacionPor");
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionSecuenciaRecurso", b =>
                {
                    b.HasOne("Plandi.Library.Models.PlaneacionSecuencia", "PlaneacionSecuencia")
                        .WithMany("Recursos")
                        .HasForeignKey("PlaneacionSecuenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlaneacionSecuencia");
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionTema", b =>
                {
                    b.HasOne("Plandi.Library.Models.PlaneacionUnidad", "PlaneacionUnidad")
                        .WithMany("Temas")
                        .HasForeignKey("PlaneacionUnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Usuario", "UltimaModificacionPor")
                        .WithMany()
                        .HasForeignKey("UltimaModificacionPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PlaneacionUnidad");

                    b.Navigation("UltimaModificacionPor");
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionTemplate", b =>
                {
                    b.HasOne("Plandi.Library.Models.Documento", "Documento")
                        .WithMany()
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionUnidad", b =>
                {
                    b.HasOne("Plandi.Library.Models.PlaneacionDidactica", "PlaneacionDidactica")
                        .WithMany("Unidades")
                        .HasForeignKey("PlaneacionDidacticaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Usuario", "UltimaModificacionPor")
                        .WithMany()
                        .HasForeignKey("UltimaModificacionPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PlaneacionDidactica");

                    b.Navigation("UltimaModificacionPor");
                });

            modelBuilder.Entity("Plandi.Library.Models.ProgramaAsignatura", b =>
                {
                    b.HasOne("Plandi.Library.Models.Academia", "Academia")
                        .WithMany()
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Plandi.Library.Models.Asignatura", "Asignatura")
                        .WithMany("ProgramasAsignatura")
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Plandi.Library.Models.Documento", "Documento")
                        .WithOne("ProgramaAsignatura")
                        .HasForeignKey("Plandi.Library.Models.ProgramaAsignatura", "DocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Usuario", "UltimaModificacionPor")
                        .WithMany()
                        .HasForeignKey("UltimaModificacionPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Academia");

                    b.Navigation("Asignatura");

                    b.Navigation("Documento");

                    b.Navigation("UltimaModificacionPor");
                });

            modelBuilder.Entity("Plandi.Library.Models.RefreshToken", b =>
                {
                    b.HasOne("Plandi.Library.Models.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Plandi.Library.Models.UserDeviceToken", b =>
                {
                    b.HasOne("Plandi.Library.Models.Usuario", "User")
                        .WithMany("UserDeviceTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Plandi.Library.Models.UsuarioRol", b =>
                {
                    b.HasOne("Plandi.Library.Models.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plandi.Library.Models.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Plandi.Library.Models.Academia", b =>
                {
                    b.Navigation("AcademiaUsuarios");

                    b.Navigation("Asignaturas");
                });

            modelBuilder.Entity("Plandi.Library.Models.Asignatura", b =>
                {
                    b.Navigation("CargasAcademicas");

                    b.Navigation("PlaneacionesDidacticas");

                    b.Navigation("ProgramasAsignatura");
                });

            modelBuilder.Entity("Plandi.Library.Models.Carrera", b =>
                {
                    b.Navigation("Grupos");
                });

            modelBuilder.Entity("Plandi.Library.Models.Chat", b =>
                {
                    b.Navigation("Mensajes");

                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("Plandi.Library.Models.CicloEscolar", b =>
                {
                    b.Navigation("Periodos");
                });

            modelBuilder.Entity("Plandi.Library.Models.Documento", b =>
                {
                    b.Navigation("ProgramaAsignatura");
                });

            modelBuilder.Entity("Plandi.Library.Models.Grupo", b =>
                {
                    b.Navigation("CargasAcademicas");
                });

            modelBuilder.Entity("Plandi.Library.Models.Periodo", b =>
                {
                    b.Navigation("Grupos");
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionDidactica", b =>
                {
                    b.Navigation("Caratula");

                    b.Navigation("Chats");

                    b.Navigation("Observaciones");

                    b.Navigation("Referencias");

                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionEtapaSecuencia", b =>
                {
                    b.Navigation("Elementos");
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionSecuencia", b =>
                {
                    b.Navigation("Recursos");
                });

            modelBuilder.Entity("Plandi.Library.Models.PlaneacionUnidad", b =>
                {
                    b.Navigation("EtapasSecuencia");

                    b.Navigation("Evaluaciones");

                    b.Navigation("Secuencias");

                    b.Navigation("Temas");
                });

            modelBuilder.Entity("Plandi.Library.Models.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Plandi.Library.Models.Usuario", b =>
                {
                    b.Navigation("AcademiaUsuarios");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserDeviceTokens");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
